### ISSUE TITLE
issue46 on Debian testing

### ISSUE THREAD

**Issue by sylvestre** [opencollab/arpack-ng#168] opened 2018-12-29 13:04 UTC
## Actual behavior

```
=======================================================
   ARPACK-NG 3.6.0: PARPACK/TESTS/MPI/test-suite.log
=======================================================

# TOTAL: 1
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  1
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: issue46
=============

--------------------------------------------------------------------------
mpirun has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpirun as a non-root user.

You can override this protection by adding the --allow-run-as-root
option to your command line.  However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
FAIL issue46 (exit status: 1)

```

With openmpi 3.1.3-6

@fghoussen Does it ring a bell? (I was going to publish a new release of arpack-ng)

**Comment by fghoussen** [comment] 2018-12-29 18:20
yes !... I had the same problem on debian/testing pulled from docker from xenial dist.

with recent openmpi, you need to add ` --allow-run-as-root --oversubscribe` when you run mpi with sudo (which seems to be the default in docker run for reason I do not know) : checkout out .travis.yml:119

which stage is broken ? interface64 ? another one ?

**Comment by sylvestre** [comment] 2018-12-29 18:39
can we make that as default ?

**Comment by fghoussen** [comment] 2018-12-29 18:40
I guess no. this is an opemmpi behavior. I think there is no such options in mpich or other mpi implementation.

**Comment by sylvestre** [comment] 2018-12-29 18:43
So, maybe we should not fail on this issue, what do you think?

**Comment by fghoussen** [comment] 2018-12-29 18:43
the problem is that `docker run` (ran from xenial- stage interface64) seems to run jobs by default as root: if there is a way (?) to run that by default as **non** root, you may have a fix...

**Comment by fghoussen** [comment] 2018-12-29 18:45
> So, maybe we should not fail on this issue, what do you think?

CI seems OK on github. Not sre to understand where this fails ?
If the failure does not break the CI, maybe one can live with that.

**Comment by fghoussen** [comment] 2018-12-29 19:36
May be related to the version of openmpi. 
If so, this problem may disappear after `sudo apt-get update` and  `sudo apt-get upgrade`.

**Comment by sylvestre** [comment] 2018-12-29 22:31
it is this bug: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=839387

**Comment by fghoussen** [comment] 2018-12-30 11:10
Would say no. Your arapck-ng issue occur with openmpi3 (not 2) and end with a "clean" error message (no crash). The problem does not occur on github CI : where does it occur ? Do you have logs available ?

**Comment by sylvestre** [comment] 2018-12-30 11:54
I would say yes as it fixed my problem :)

**Comment by fghoussen** [comment] 2018-12-30 12:45
> I would say yes as it fixed my problem :)

:+1: => closing #171 as it fails with :

```
make[3]: Entering directory '/tmp/arpack-ng/PARPACK/TESTS/MPI'
make[4]: Entering directory '/tmp/arpack-ng/PARPACK/TESTS/MPI'
FAIL: issue46
FAIL: icb_parpack_c
FAIL: icb_parpack_cpp
=======================================================
   ARPACK-NG 3.6.0: PARPACK/TESTS/MPI/test-suite.log
=======================================================

# TOTAL: 3
# PASS:  0
# SKIP:  0
# XFAIL: 0
# FAIL:  3
# XPASS: 0
# ERROR: 0

.. contents:: :depth: 2

FAIL: issue46
=============

--------------------------------------------------------------------------
mpirun has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpirun as a non-root user.

You can override this protection by adding the --allow-run-as-root
option to your command line.  However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
FAIL issue46 (exit status: 1)

FAIL: icb_parpack_c
===================

--------------------------------------------------------------------------
mpirun has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpirun as a non-root user.

You can override this protection by adding the --allow-run-as-root
option to your command line.  However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------
FAIL icb_parpack_c (exit status: 1)

FAIL: icb_parpack_cpp
=====================

--------------------------------------------------------------------------
mpirun has detected an attempt to run as root.

Running as root is *strongly* discouraged as any mistake (e.g., in
defining TMPDIR) or bug can result in catastrophic damage to the OS
file system, leaving your system in an unusable state.

We strongly suggest that you run mpirun as a non-root user.

You can override this protection by adding the --allow-run-as-root
option to your command line.  However, we reiterate our strong advice
against doing so - please do so at your own risk.
--------------------------------------------------------------------------

```

**Closed** 2019-01-12 14:51 UTC
